import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const schema = readFileSync(new URL('../prisma/schema.prisma', import.meta.url), 'utf8');
const reactionsLib = readFileSync(new URL('../lib/reactions.ts', import.meta.url), 'utf8');
const customEmojiActions = readFileSync(new URL('../app/actions/custom-emoji.ts', import.meta.url), 'utf8');
const postActions = readFileSync(new URL('../app/actions/post.ts', import.meta.url), 'utf8');
const feed = readFileSync(new URL('../components/Feed.tsx', import.meta.url), 'utf8');
const singlePost = readFileSync(new URL('../components/SinglePost.tsx', import.meta.url), 'utf8');
const sidebar = readFileSync(new URL('../components/Sidebar.tsx', import.meta.url), 'utf8');
const customEmojiPage = readFileSync(new URL('../app/custom-emojis/page.tsx', import.meta.url), 'utf8');
const customEmojiManager = readFileSync(new URL('../app/custom-emojis/CustomEmojiManager.tsx', import.meta.url), 'utf8');
const customEmojiRoute = readFileSync(new URL('../app/api/custom_emoji/[filename]/route.ts', import.meta.url), 'utf8');
const clientUpload = readFileSync(new URL('../lib/client-upload.ts', import.meta.url), 'utf8');
const clientCustomEmojis = readFileSync(new URL('../lib/client-custom-emojis.ts', import.meta.url), 'utf8');

assert.match(schema, /model CustomEmoji\s*{[\s\S]*name\s+String[\s\S]*imageUrl\s+String[\s\S]*storagePath\s+String[\s\S]*width\s+Int[\s\S]*height\s+Int[\s\S]*creatorId\s+Int[\s\S]*isActive\s+Boolean\s+@default\(true\)[\s\S]*@@unique\(\[name\]\)/, 'CustomEmoji model should store shared named image emoji metadata without embedding image bytes');
assert.match(schema, /customEmojiId\s+Int\?/, 'PostReaction should optionally reference a custom emoji');
assert.match(schema, /customEmoji\s+CustomEmoji\?\s+@relation/, 'PostReaction should relate to CustomEmoji for rendering metadata');
assert.match(reactionsLib, /CUSTOM_REACTION_PREFIX\s*=\s*["']custom:["']/, 'reaction keys should support custom:<id>');
assert.match(reactionsLib, /normalizeCustomEmojiName/, 'custom emoji names should be normalized consistently');
assert.match(reactionsLib, /normalizeReactionKey[\s\S]*custom:/, 'reaction normalization should accept custom emoji keys');
assert.match(reactionsLib, /customEmoji\?:/, 'reaction summaries should carry custom emoji metadata');
assert.match(customEmojiActions, /export async function createCustomEmoji/, 'users should be able to create custom emoji');
assert.match(customEmojiActions, /export async function fetchCustomEmojis/, 'clients should be able to fetch shared custom emoji');
assert.match(customEmojiActions, /creatorId:\s*true/, 'custom emoji list should include creatorId so only the owner can edit');
assert.match(customEmojiActions, /creator:\s*{\s*select:\s*{\s*username:\s*true/, 'custom emoji list should include the creator username for the management list');
assert.match(customEmojiActions, /unstable_cache|revalidateTag/, 'custom emoji list should use Next cache and invalidate after creation');
assert.match(customEmojiActions, /image\/(png|jpeg|jpg|gif|webp)/, 'custom emoji creation should restrict image MIME types');
assert.match(customEmojiActions, /data:image|base64/, 'server action should explicitly reject inline/base64 image storage');
assert.match(customEmojiActions, /width\s*!==\s*128|height\s*!==\s*128/, 'server action should require normalized 128x128 emoji images');
assert.match(customEmojiActions, /normalizeCustomEmojiName/, 'server action should validate custom emoji names');
assert.match(customEmojiActions, /db\.customEmoji\.delete/, 'deleting a custom emoji should remove it from the database so the name can be reused');
assert.match(customEmojiActions, /db\.customEmoji\.deleteMany\(\{[\s\S]*where:\s*\{\s*name,[\s\S]*isActive:\s*false/, 'creating a custom emoji should purge old soft-deleted rows with the same name before checking uniqueness');
assert.match(postActions, /customEmoji:\s*{\s*select:\s*{[\s\S]*name:\s*true[\s\S]*imageUrl:\s*true/, 'post queries should include custom emoji metadata for reaction chips');
assert.match(postActions, /customEmojiId/, 'toggleReaction should persist the custom emoji relation');
assert.match(feed, /loadCustomEmojis/, 'Feed picker should load shared custom emoji');
assert.doesNotMatch(feed, /createCustomEmoji|uploadCustomEmojiImage|showCustomEmojiUploadForm|type=\"file\"/, 'Feed picker must not contain custom emoji creation UI');
assert.doesNotMatch(feed, /オブジェクトストレージに保存/, 'Feed UI must not expose storage implementation details to users');
assert.match(feed, /getCustomEmojiImageSrc/, 'Feed should render custom emoji images through the shared client helper');
assert.match(feed, /width=\{24\}[\s\S]*height=\{24\}[\s\S]*h-6 w-6/, 'Feed reaction chips should render custom emoji large enough while preserving chip balance');
assert.doesNotMatch(feed, /border-dashed/, 'Feed picker should not put custom emoji in a special dashed frame');
assert.match(singlePost, /loadCustomEmojis/, 'SinglePost picker should load shared custom emoji');
assert.doesNotMatch(singlePost, /createCustomEmoji|uploadCustomEmojiImage|showCustomEmojiUploadForm|type=\"file\"/, 'SinglePost picker must not contain custom emoji creation UI');
assert.doesNotMatch(singlePost, /オブジェクトストレージに保存/, 'SinglePost UI must not expose storage implementation details to users');
assert.match(singlePost, /getCustomEmojiImageSrc/, 'SinglePost should render custom emoji images through the shared client helper');
assert.match(singlePost, /width=\{24\}[\s\S]*height=\{24\}[\s\S]*h-6 w-6/, 'SinglePost reaction chips should render custom emoji large enough while preserving chip balance');
assert.doesNotMatch(singlePost, /border-dashed/, 'SinglePost picker should not put custom emoji in a special dashed frame');
assert.match(sidebar, /カスタム絵文字[\s\S]*href:\s*['"]\/custom-emojis['"]/, 'Sidebar should expose custom emoji management from the hamburger/sidebar menu');
assert.match(customEmojiPage, /CustomEmojiManager/, 'custom emoji management page should render the manager');
assert.match(customEmojiManager, /uploadCustomEmojiImage[\s\S]*createCustomEmoji/, 'custom emoji manager should create emoji outside the reaction picker');
assert.match(customEmojiManager, /updateCustomEmoji[\s\S]*deleteCustomEmoji/, 'custom emoji manager should support editing and deleting existing emoji');
assert.match(customEmojiManager, /canEditEmoji\(emoji\)/, 'custom emoji manager should only enable editing controls for the owner');
assert.match(customEmojiManager, /hasEmojiChanged\(emoji\)/, 'custom emoji save button should activate only after changes');
assert.match(customEmojiManager, /emoji\.creator\?\.username\.toLowerCase\(\)/, 'custom emoji manager should show the creator username in lowercase');
assert.match(customEmojiManager, /text-xs[\s\S]*作成者/, 'custom emoji creator should be rendered as small text');
assert.match(customEmojiManager, /text-right[\s\S]*作成者/, 'custom emoji creator should be on its own row aligned to the lower right');
assert.match(customEmojiManager, /htmlFor="custom-emoji-file"[\s\S]*ファイルを選択/, 'custom emoji file input should be presented as a proper button');
assert.match(customEmojiRoute, /db\.customEmoji\.findUnique[\s\S]*fetch\(customEmoji\.imageUrl\)/, 'custom emoji images should be served through a same-origin proxy route');
assert.match(clientCustomEmojis, /let customEmojiCache/, 'client custom emoji helper should memoize the fetched emoji list');
assert.match(clientCustomEmojis, /warmCustomEmojis[\s\S]*requestIdleCallback/, 'client custom emoji helper should warm the picker cache during idle time');
assert.match(clientCustomEmojis, /preloadCustomEmojiImages[\s\S]*new Image\(\)/, 'client custom emoji helper should preload custom emoji images before the picker opens');
assert.match(clientCustomEmojis, /\/api\/custom_emoji\/\$\{customEmoji\.id\}\.webp/, 'client custom emoji helper should keep browser rendering on the same-origin proxy route');
assert.match(customEmojiRoute, /unstable_cache[\s\S]*custom-emoji:image/, 'custom emoji proxy route should cache metadata lookup before fetching the image');
assert.match(customEmojiRoute, /new NextResponse\(response\.body/, 'custom emoji proxy route should stream upstream image bytes instead of buffering the whole file');
assert.match(reactionsLib, /絵文字名は2〜32文字で、半角英小文字・数字・アンダースコアのみ使用できます。/, 'custom emoji validation message should be Japanese');
assert.doesNotMatch(reactionsLib, /Custom emoji name must/, 'custom emoji validation should not expose English errors');
assert.match(clientUpload, /export async function prepareCustomEmojiUpload/, 'client upload helper should normalize custom emoji images before storage upload');
assert.match(clientUpload, /canvas\.width\s*=\s*128[\s\S]*canvas\.height\s*=\s*128/, 'custom emoji uploads should be resized to a square 128x128 canvas');
assert.match(clientUpload, /Math\.min\(scaleX, scaleY\)/, 'custom emoji resizing should preserve aspect ratio without distortion');
assert.match(clientUpload, /loadImageElement[\s\S]*URL\.createObjectURL/, 'PNG uploads should fall back to an HTMLImageElement decode path when createImageBitmap cannot decode the source');
assert.match(clientUpload, /画像を読み込めませんでした。/, 'custom emoji upload decode errors should be shown in Japanese');
assert.match(clientUpload, /custom-emojis/, 'custom emoji helper should upload to object storage custom-emojis folder');
