import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const schema = readFileSync(new URL('../prisma/schema.prisma', import.meta.url), 'utf8');
const reactionsLib = readFileSync(new URL('../lib/reactions.ts', import.meta.url), 'utf8');
const customEmojiActions = readFileSync(new URL('../app/actions/custom-emoji.ts', import.meta.url), 'utf8');
const postActions = readFileSync(new URL('../app/actions/post.ts', import.meta.url), 'utf8');
const feed = readFileSync(new URL('../components/Feed.tsx', import.meta.url), 'utf8');
const singlePost = readFileSync(new URL('../components/SinglePost.tsx', import.meta.url), 'utf8');
const clientUpload = readFileSync(new URL('../lib/client-upload.ts', import.meta.url), 'utf8');

assert.match(schema, /model CustomEmoji\s*{[\s\S]*name\s+String[\s\S]*imageUrl\s+String[\s\S]*storagePath\s+String[\s\S]*width\s+Int[\s\S]*height\s+Int[\s\S]*creatorId\s+Int[\s\S]*isActive\s+Boolean\s+@default\(true\)[\s\S]*@@unique\(\[name\]\)/, 'CustomEmoji model should store shared named image emoji metadata without embedding image bytes');
assert.match(schema, /customEmojiId\s+Int\?/, 'PostReaction should optionally reference a custom emoji');
assert.match(schema, /customEmoji\s+CustomEmoji\?\s+@relation/, 'PostReaction should relate to CustomEmoji for rendering metadata');
assert.match(reactionsLib, /CUSTOM_REACTION_PREFIX\s*=\s*["']custom:["']/, 'reaction keys should support custom:<id>');
assert.match(reactionsLib, /normalizeCustomEmojiName/, 'custom emoji names should be normalized consistently');
assert.match(reactionsLib, /normalizeReactionKey[\s\S]*custom:/, 'reaction normalization should accept custom emoji keys');
assert.match(reactionsLib, /customEmoji\?:/, 'reaction summaries should carry custom emoji metadata');
assert.match(customEmojiActions, /export async function createCustomEmoji/, 'users should be able to create custom emoji');
assert.match(customEmojiActions, /export async function fetchCustomEmojis/, 'clients should be able to fetch shared custom emoji');
assert.match(customEmojiActions, /unstable_cache|revalidateTag/, 'custom emoji list should use Next cache and invalidate after creation');
assert.match(customEmojiActions, /image\/(png|jpeg|jpg|gif|webp)/, 'custom emoji creation should restrict image MIME types');
assert.match(customEmojiActions, /data:image|base64/, 'server action should explicitly reject inline/base64 image storage');
assert.match(customEmojiActions, /width\s*!==\s*128|height\s*!==\s*128/, 'server action should require normalized 128x128 emoji images');
assert.match(customEmojiActions, /normalizeCustomEmojiName/, 'server action should validate custom emoji names');
assert.match(postActions, /customEmoji:\s*{\s*select:\s*{[\s\S]*name:\s*true[\s\S]*imageUrl:\s*true/, 'post queries should include custom emoji metadata for reaction chips');
assert.match(postActions, /customEmojiId/, 'toggleReaction should persist the custom emoji relation');
assert.match(feed, /fetchCustomEmojis/, 'Feed picker should load shared custom emoji');
assert.match(feed, /createCustomEmoji/, 'Feed picker should allow creating a custom emoji');
assert.match(feed, /uploadCustomEmojiImage/, 'Feed should upload custom emoji images through the object-storage custom emoji helper');
assert.match(feed, /customEmoji\.imageUrl/, 'Feed should render custom emoji images');
assert.match(singlePost, /fetchCustomEmojis/, 'SinglePost picker should load shared custom emoji');
assert.match(singlePost, /createCustomEmoji/, 'SinglePost picker should allow creating a custom emoji');
assert.match(singlePost, /uploadCustomEmojiImage/, 'SinglePost should upload custom emoji images through the object-storage custom emoji helper');
assert.match(singlePost, /customEmoji\.imageUrl/, 'SinglePost should render custom emoji images');
assert.match(clientUpload, /export async function prepareCustomEmojiUpload/, 'client upload helper should normalize custom emoji images before storage upload');
assert.match(clientUpload, /canvas\.width\s*=\s*128[\s\S]*canvas\.height\s*=\s*128/, 'custom emoji uploads should be resized to a square 128x128 canvas');
assert.match(clientUpload, /Math\.min\(scaleX, scaleY\)/, 'custom emoji resizing should preserve aspect ratio without distortion');
assert.match(clientUpload, /custom-emojis/, 'custom emoji helper should upload to object storage custom-emojis folder');
